# -*- coding: utf-8 -*-
"""Carts - Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEygBjhu2LCmvm2xzYYRbfMsXG2yvJlk
"""

# ----------------- STEP 1: Install Required Packages -----------------
!pip install mlxtend openpyxl --quiet

# ----------------- STEP 2: Import Libraries -----------------
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from tabulate import tabulate

# Suppress DeprecationWarnings globally
warnings.filterwarnings("ignore", category=DeprecationWarning)

# ----------------- STEP 3: Load Datasets -----------------
# Transaction dataset (CSV)
transactions_df = pd.read_csv("/content/drive/MyDrive/AIML/CARTS_datasets/TransactionDatasetCarts.csv")

# Item Master dataset (Excel)
item_master_df = pd.read_excel("/content/drive/MyDrive/AIML/CARTS_datasets/ItemMasterCarts.xlsx")

print("Sample Transactions Data:")
print(transactions_df.head())

print("\nItem Master Data:")
print(item_master_df.head())

# ----------------- STEP 4: Data Preprocessing -----------------
# 4.1 Drop first column ("Item(s)")
transactions_only = transactions_df.drop(columns=[transactions_df.columns[0]], errors="ignore")

# 4.2 Clean values: strip strings, remove NaN
transactions_only = transactions_only.applymap(lambda x: str(x).strip() if pd.notna(x) else None)


# 4.3 Convert rows into list of items
transactions = transactions_only.apply(lambda row: [item for item in row if item], axis=1).tolist()

print("\nSample Processed Transactions (first 5):")
for i, t in enumerate(transactions[:5], 1):
    print(f"Transaction {i}: {t}")

# ----------------- STEP 5: One-Hot Encoding -----------------
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
ohe_df = pd.DataFrame(te_ary, columns=te.columns_)

print("\nOne-Hot Encoded Transactions Matrix:")
print(ohe_df.head())

# ----------------- STEP 6: Run Apriori -----------------
min_support = 0.05  # adjustable
freq_itemsets = apriori(ohe_df, min_support=min_support, use_colnames=True, verbose=1)

print("\nFrequent Itemsets (Apriori Results):")
print(freq_itemsets.head())

# ----------------- STEP 7: Generate Association Rules -----------------
rules = association_rules(freq_itemsets, metric="lift", min_threshold=1.0)

# Convert frozensets to strings and clean
rules['antecedents'] = rules['antecedents'].apply(lambda x: ', '.join(sorted([i for i in x if str(i).lower() != 'nan'])) if isinstance(x, frozenset) else x)
rules['consequents'] = rules['consequents'].apply(lambda x: ', '.join(sorted([i for i in x if str(i).lower() != 'nan'])) if isinstance(x, frozenset) else x)


# Drop empty rules
rules = rules[(rules['antecedents'] != '') & (rules['consequents'] != '')].reset_index(drop=True)

print("\nAssociation Rules (Cleaned):")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].to_string(index=False))

# ----------------- STEP 8: Recommendation Function -----------------
def recommend_items(user_cart, rules_df, top_n=5):
    recommendations = []
    cart_set = set(user_cart)

    for _, row in rules_df.iterrows():
        antecedents = set(row['antecedents'].split(", "))

        # Match if user_cart shares ANY item with antecedents
        if cart_set & antecedents:
            recommendations.extend(row['consequents'].split(", "))

    # Remove already purchased items
    recommendations = [item for item in recommendations if item not in user_cart]

    # Fallback: if empty, suggest top frequent items
    if not recommendations:
        fallback = freq_itemsets.sort_values("support", ascending=False)
        fallback_items = [', '.join(map(str, i)) for i in fallback['itemsets']]
        return fallback_items[:top_n]

    # Return most common recommendations
    return list(pd.Series(recommendations).value_counts().head(top_n).index)

# ----------------- Step 9: Function to Show Products -----------------
def show_products(df):
    print("\n Available Products in Store ===")
    print("-" * 70)

    # Use the correct column name from your dataset
    if "Item Names" in df.columns:
        items = df["Item Names"].unique()
    else:
        raise KeyError("Column 'Item Names' not found in Item Master!")

    for idx, item in enumerate(items, 1):
        print(f"{idx}. {item}")

# ---------------------------- STEP 10: Test Recommendation --------------------------------
show_products(item_master_df)   # shows all available products

# Take user input for basket
user_input = input("Enter items in your basket (separated by commas): ")

# Convert input string into a list (strip removes extra spaces)
sample_basket = [item.strip() for item in user_input.split(",")]

# Generate recommendations
recommended_items = recommend_items(sample_basket, rules, top_n=5)

print("\nApriori Recommendation Result:")
print("Items in Cart:", sample_basket)
print("Top 5 Recommended Items:")
for idx, item in enumerate(recommended_items, 1):
    print(f"{idx}. {item}")

def show_recommendation_table(purchased, recommended):
    purchased_str = ", ".join([item.title() for item in purchased])
    recommended_str = ", ".join([item.title() for item in recommended])

    table = [[purchased_str, recommended_str]]
    headers = ["Purchased Basket", "Recommended Items"]

    print("\nRecommendation Table:")
    print(tabulate(table, headers=headers, tablefmt="grid"))


show_recommendation_table(sample_basket, recommended_items)

